export default // 20220914121833
// https://api.github.com/users/Llydo1

{
  login: "Llydo1",
  id: 94525521,
  node_id: "U_kgDOBaJYUQ",
  avatar_url: "https://avatars.githubusercontent.com/u/94525521?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Llydo1",
  html_url: "https://github.com/Llydo1",
  followers_url: "https://api.github.com/users/Llydo1/followers",
  following_url: "https://api.github.com/users/Llydo1/following{/other_user}",
  gists_url: "https://api.github.com/users/Llydo1/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Llydo1/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Llydo1/subscriptions",
  organizations_url: "https://api.github.com/users/Llydo1/orgs",
  repos_url: "https://api.github.com/users/Llydo1/repos",
  events_url: "https://api.github.com/users/Llydo1/events{/privacy}",
  received_events_url: "https://api.github.com/users/Llydo1/received_events",
  type: "User",
  site_admin: false,
  name: "Llydo1",
  company: "Heheboi",
  blog: "Heheboi",
  location: "Heheboi",
  email: null,
  hireable: null,
  bio: "Heheboi\r\n",
  twitter_username: "Heheboi",
  public_repos: 21,
  public_gists: 0,
  followers: 5,
  following: 1,
  created_at: "2021-11-17T09:10:13Z",
  updated_at: "2022-09-14T05:17:58Z",
};
